### ISSUE TITLE
Create CDK code to basic Rollups Infra

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#1]
We should import some CDK code from cartesi-rollups infra but make adjusts for best practices during the process.

- [ ] Postgres RDS should be on a separate Stack
- [ ] Pack Constructs into self-contained modules
- [ ] Reuse the constructs in separate Stacks if needed
- [ ] ...

References:
- https://github.com/kevinslin/open-cdk
- https://aws.amazon.com/blogs/devops/best-practices-for-developing-cloud-applications-with-aws-cdk/
- https://docs.aws.amazon.com/cdk/v2/guide/best-practices.html

**Comment by tuler** [comment]
Not relevant any longer
