### ISSUE TITLE
`sunodo send generic` produces larger payloads padded with zeroes when `hex` encoding is explicitly specified

### ISSUE THREAD

**Issue by miltonjonat** [sunodo/sunodo#130]
## 🙂 Expected behavior

Running the following commands would be expected to produce the same payload `0xdeadbeef`:

- `sunodo send generic --input "0xdeadbeef"`
- `sunodo send generic --input "deadbeef" --input-encoding "hex"`

## 🫠 Actual behavior

The first command produces the exact payload `0xdeadbeef`, while the second one produces the payload `0xdeadbeef00000000`

## 🧪 Minimal test case

Just run the above commands.

## 🌎 Environment

Sunodo 0.6, Rollups 0.9

## ✔️ Possible solutions

I don't really know what is going on. I have tested some similar payloads that indicate that, when using explicit "hex" encoding, the resulting payload is always double the original size, padded with zeroes:

- `sunodo send generic --input "deadbe" --input-encoding "hex"`
  - payload: `0xdeadbe000000`
- `sunodo send generic --input "dead" --input-encoding "hex"`
  - payload: `0xdead0000`
- `sunodo send generic --input "de" --input-encoding "hex"`
  - payload: `0xde00`

**Comment by tuler** [comment]
Got the bug.
