### ISSUE TITLE
Improve handling of `sunodo send generic` when specifying hex encoding and an input starting with `0x`

### ISSUE THREAD

**Issue by miltonjonat** [sunodo/sunodo#131]
## 🙂 Expected behavior

If a user runs the following command:
```
sunodo send generic --input-encoding "hex" --input "0xdeadbeef"
```

One of two outcomes would be expected:
- sunodo could ignore the `0x` prefix and just send the input (as would happen if no encoding was specified)
- sunodo could inform the user that he should not use the `0x` prefix with this setup

## 🫠 Actual behavior

Sunodo is printing the following message:
```
Error: input encoded as hex must start with 0x
```

Which is quite confusing to the user, IMHO. Aside from that, there is no indication in the command description that the `0x` prefix should be avoided when `hex` encoding is specified.

## 🧪 Minimal test case

Just run the above command

## 🌎 Environment

Sunodo 0.6, Rollups 0.9

## ✔️ Possible solutions

From a user's perspective, I would personally prefer Sunodo to handle the `0x` prefix, so that `sunodo send generic --input-encoding "hex" --input "0xdeadbeef"` and `sunodo send generic --input "0xdeadbeef"` work the same.

If not, then I think the help should include the information that the `0x` prefix should be avoided, and the error message should be fixed/improved.

**Comment by tuler** [comment]
I did not understand why the error message is not clear.

```
Error: input encoded as hex must start with 0x
```

Meaning the `--input` value must start with `0x`.

**Comment by tuler** [comment]
Got the bug.

**Comment by tuler** [comment]
https://github.com/sunodo/sunodo/pull/132
