### ISSUE TITLE
When I execute `sunodo run` there is no feedback about the local Ethereum node address.

### ISSUE THREAD

**Issue by claudioantonio** [sunodo/sunodo#136]
## 📚 Context

When I execute `sunodo run` I am informed about the GraphQL and Inspect servers addresses but not about the local Ethereum node address.

## 🎯 Definition of Done

-   [ ] A feedback after executing `sunodo run` that shows the graphql server, inspect server and local Ethereum node addresses like shown below.
Ethereum node ready: http://localhost:8545
GraphQL Server ready: http://localhost:8080/graphql
Inspect Server ready: http://localhost:8080/inspect

**Comment by claudioantonio** [comment]
@tuler and @endersonmaia  is the fix simple as adding an extra line on the following file?
[packages/rollups-node/s6-overlay/s6-rc.d/traefik/run](https://github.com/sunodo/sunodo/blob/76d799ff059ea36e937a29c2369195e0fd18951a/packages/rollups-node/s6-overlay/s6-rc.d/traefik/run)

**Comment by tuler** [comment]
Not exactly. The ethereum node is not part of the rollups-node.

It’s part of the compose environment.

Just a note there is also a `verbose` option in the `run` command.

**Comment by tuler** [comment]
Added in sunodo 0.9.0
