### ISSUE TITLE
Sunodo send must ask for DApp address

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#154]
## 🙂 Expected behavior

`sunodo send` must ask for DApp address if not defined by the command flag `--dapp`.

## 🫠 Actual behavior

If not defined by `--dapp` the address is being resolved from the local execution environment address of deployed DApp.

But the destination of input can be a testnet or mainnet environment, so it doesn't make sense.

## 🧪 Minimal test case

Run `sunodo send` and choose a testnet.

## ✔️ Possible solutions

We can still resolve the local execution DApp address as the default input value in case the chosen chain is the devnet.

**Comment by endersonmaia** [comment]
While testing te PR #165 , I can't use `sunodo run` to send inputs to a dapp running with the `--no-backend` argument.

`sunodo run` looks for a machine-snapshot and asks the user to run `sunodo build`.

```
> sunodo send
? Select send sub-command Send generic input to the application.
? Chain Foundry
? RPC URL http://127.0.0.1:8545
? Wallet Mnemonic
? Mnemonic test test test test test test test test test test test junk
? Account 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 9999.969241350387558666 ETH
    Error: Cartesi machine snapshot not found, run 'sunodo build'
```

**Comment by tuler** [comment]
I think the main problem lies in how we are calculating the address book.
The address book is composed by:
- addresses of Cartesi Rollups contracts
- address of a deployed DApp

The addresses of the Cartesi Rollups contracts is currently being copied from the file `/usr/share/sunodo/localhost.json` inside de `anvil` docker container of a running node. (So the node must be running).

The address of the DApp is currently being copied from the file `/usr/share/sunodo/dapp.json` inside de `anvil` docker container of a running node. (So the node must be running).

We must know the name of the container to know where to copied theses files from.
We use the hash of the machine as the docker project name.

In case of the implementation of PR https://github.com/sunodo/sunodo/pull/165 there is no machine. And we are using `sunodo-node` as the project name. Which by the way only works for a single node in the user machine.
