### ISSUE TITLE
Lock DOCKER_API_VERSION instead of relying on docker cli version

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#274]
## 📚 Context

Since we're using docker CLI as an interface to docker, we should lock our interaction using the DOCKER_API_VERSION, this way we avoid problems with different docker versions from different docker users.

This way we can update the API with more control, when we need some functionality for new API versions.

## ✔️ Solution

Lock the DOCKER_API_VERSION.

https://docs.docker.com/engine/api/

## 📈 Subtasks

-   [ ] See where we should lock the version
-   [ ] Adapt `sunodo doctor` to check for the API version instead of the CLI version.

**Comment by tuler** [comment]
I tried using the Docker API directly in the beginning of the project.
It's way harder than using the CLI.

**Comment by endersonmaia** [comment]
To run everything, we're using mainly `docker compose` cli, other commands we use to check the status or version, we could try to use the API, it may be easier.

And I found this project, don't know if you already assessed it https://github.com/apocas/dockerode-compose

**Comment by tuler** [comment]
> And I found this project, don't know if you already assessed it https://github.com/apocas/dockerode-compose

I did. It's very immature.
