### ISSUE TITLE
released container artifacts has wrong latest tags

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#280]
## 🙂 Expected behavior

sunodo container releases should point the `:latest` tag to that latest release.

## 🫠 Actual behavior

- `sunodo/rollups-node:latest` - Oct 3, 2023 at 5:11 pm
- `sunodo/rollups-node:0.5.1` - Oct 24, 2023 at 3:25 pm

## ✔️ Possible solutions

- [x] Fix the CI to also release the latest tag for all container artifacts
- [ ] Point the latest tag to all already released container artifacts and not wait for the next CI run

**Comment by endersonmaia** [comment]
About this issue, acctually, our GitHub Container registry has some gaps form some releases that was being done manually while we were fixing our CI.

**Comment by tuler** [comment]
Can we close this issue, since we don't have a sunodo/rollups-node anymore?
