### ISSUE TITLE
make tags/release names consitent between packages

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#282]
## 📚 Context

This is a monorepo, and we have some `packages/` (mainly container images) and `apps/` mainly npm packages.

We started giving packages different names based on their types.

No npm packages are named like `@sunodo/cli`, and the container image packages are named like `rollups-node`.

The problem is that we get a GitHub Release pages without a consistent naming, and also the git tags.

## ✔️ Solution

Make the naming consistent between packages.

I propose using the same `@sunodo/` prefix for all packages, no matter if they're npm package or not.

And also use the same strategy for tags.

## 📈 Subtasks

-   [x] Add `@sunodo/` prefix for packages that are mising
-   [x] add git tag retroactively

**Comment by endersonmaia** [comment]
Partially solved at #286, #289

**Comment by tuler** [comment]
Can we close this @endersonmaia ?

**Comment by endersonmaia** [comment]
I was not sure how to fix the old tags/releases. If it's not necessary, this can be closed.

**Comment by tuler** [comment]
You mean git tags? We can manually add the old git tags.

**Comment by endersonmaia** [comment]
git tags and github releases

**Comment by endersonmaia** [comment]
git tags done:

```
git tag @sunodo/rollups-node@0.1.1 rollups-node@0.1.0 ; git push origin @sunodo/rollups-node@0.1.0
git tag @sunodo/rollups-node@0.1.1 rollups-node@0.1.1 ; git push origin @sunodo/rollups-node@0.1.1
git tag @sunodo/rollups-node@0.2.0 rollups-node@0.2.0 ; git push origin @sunodo/rollups-node@0.2.0
git tag @sunodo/rollups-node@0.3.0 rollups-node@0.3.0 ; git push origin @sunodo/rollups-node@0.3.0
git tag @sunodo/rollups-node@0.4.0 rollups-node@0.4.0 ; git push origin @sunodo/rollups-node@0.4.0
git tag @sunodo/rollups-node@0.4.1 rollups-node@0.4.1 ; git push origin @sunodo/rollups-node@0.4.1
git tag @sunodo/rollups-node@0.5.0 rollups-node@0.5.0 ; git push origin @sunodo/rollups-node@0.5.0
git tag @sunodo/rollups-node@0.5.1 rollups-node@0.5.1 ; git push origin @sunodo/rollups-node@0.5.1


git tag @sunodo/anvil@2.0.0 anvil@2.0.0 ; git push origin @sunodo/anvil@2.0.0
git tag @sunodo/anvil@2.0.1 anvil@2.0.1 ; git push origin @sunodo/anvil@2.0.1
git tag @sunodo/anvil@3.0.0 anvil@3.0.0 ; git push origin @sunodo/anvil@3.0.0
git tag @sunodo/anvil@3.1.0 anvil@3.1.0 ; git push origin @sunodo/anvil@3.1.0
git tag @sunodo/anvil@3.2.0 anvil@3.2.0 ; git push origin @sunodo/anvil@3.2.0
```
