### ISSUE TITLE
devnet build error when  trying to build sunodo from WSL2

### ISSUE THREAD

**Issue by jplgarcia** [sunodo/sunodo#343]
## 🙂 Expected behavior
Finding the EACCESS error I tried to build the cli from the branch: https://github.com/sunodo/sunodo/tree/feature/use-volumes-instead-of-bind-mount

Ideally it would build normally following `yarn && yarn build` or `(cd apps/cli; yarn && yarn build)` everything should run properly including the build of the devnet package

## 🫠 Actual behavior

It seems that after yarn && yarn build the hardhat compile command finds nothing to compile and this leads to a series of errors as shown below:

```
john@DESKTOP-AGNT5V1:~/sunododev/sunodo/packages/devnet$ yarn build
yarn run v1.22.21
$ run-s compile export deploy:anvil build:docker
$ hardhat compile
Nothing to compile
$ hardhat export-artifacts export/artifacts --hide-sources --including-empty-bytecode --including-no-public-functions
Nothing to compile
$ hardhat --network localhost deploy-anvil --dump-file build/anvil_state.json --silent
deploying to anvil and dumping state to build/anvil_state.json
Error: spawn anvil ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "deploy:anvil" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🧪 Minimal test case

For this test I cloned the repo, switched to the branch: 
https://github.com/sunodo/sunodo/tree/feature/use-volumes-instead-of-bind-mount
And updated the Anvil version as follows, switching from "3d6bfddf1e9335c623ba47b590da532f8d785ef4" to "6fc74638b797b8e109452d3df8e26758f86f31fe":

```
 # download pre-compiled binaries
-ARG ANVIL_VERSION=3d6bfddf1e9335c623ba47b590da532f8d785ef4
+ARG ANVIL_VERSION=6fc74638b797b8e109452d3df8e26758f86f31fe
 RUN curl -sSL https://github.com/foundry-rs/foundry/releases/download/nightly-${ANVIL_VERSION}/foundry_nightly_linux_$(dpkg --print-architecture).tar.gz | \
     tar -zx -C /usr/local/bin
```

## 🌎 Environment

Windows using WSL 2 and Docker Desktop for Windows
WSL: Ubuntu: 22.04.3 LTS
Node version: v20.10.0
Yarn version: 1.22.21
Docker version: 24.0.6, build ed223bc

**Comment by tuler** [comment]
You need to [install anvil](https://book.getfoundry.sh/getting-started/installation#using-foundryup).

This should be somewhere in the README, but I guess it's not.

**Comment by jplgarcia** [comment]
With anvil installed it works, thanks!
