### ISSUE TITLE
sunodo init

### ISSUE THREAD

**Issue by omidasadpour** [sunodo/sunodo#372]
## 📚 Context

If the user's system does not have the required packages and tools sunodo can't run in it. 

## ✔️ Solution

We could have an `init` sub-command to work along with `doctor` sub-command to check the dependencies required for sunodo, such as Docker and ... . When it does not exist or the version is too low, it can be installed automatically.

## 📈 Subtasks

-   [ ] init sub-command

## 🎯 Definition of Done

-   [ ] the sub command should run successfully and install each required tools based on the user's OS.

**Comment by tuler** [comment]
You mean install docker desktop?

**Comment by tuler** [comment]
The installation procedure of Docker Desktop for Mac from a command line application is quite frightening. Lots to go wrong there.

https://docs.docker.com/desktop/install/mac-install/

**Comment by oap75** [comment]
> The installation procedure of Docker Desktop for Mac from a command line application is quite frightening. Lots to go wrong there.

your right. But we can start from other required tools. 

Also, I think this is a good script example for docker desktop. (https://get.docker.com/)

**Comment by tuler** [comment]
> Also, I think this is a good script example for docker desktop. (https://get.docker.com/)

This is for Docker Engine on Linux, not Docker Desktop, which is what we recommend.

**Comment by oap75** [comment]
> > Also, I think this is a good script example for docker desktop. (https://get.docker.com/)
> 
> This is for Docker Engine on Linux, not Docker Desktop, which is what we recommend.

It was just an example to show the idea. 

if you think it's quite frightening. then `init` sub-command can skip the docker desktop installation and just prompt an instructions or refer to  links to install it.
