### ISSUE TITLE
Sunodo read for output reading

### ISSUE THREAD

**Issue by jplgarcia** [sunodo/sunodo#419]
## 📚 Context

There are multiples APIs to read information from the dApp and all of them return the data on hex format, a simple read command could help and be integrated with the main CLI for devs to easily read outputs. 

## ✔️ Solution

A possible solution would be a subcommand for sunodo to read the outputs and already convert hex to string so it's easy digestible and a good way to test this. This could even be used for inspect calls just performing the get and then hex2str.

## 🎯 Definition of Done

-   `sunodo read reports`, `sunodo read vouchers`, `sunodo read notices` for graphql api and `sunodo read inspect` for inspect calls or something akin to this

**Comment by tuler** [comment]
I'm not a big fan of commands for reading graphql info. We already have the graphql endpoint and the explorer (which will be updated in the next release).
The conversion of binary data to string is very opinionated IMO. If this was implemented we would have to provide options for decoding, similar to what we do in the send commands.

What I like best is to implement the read from graphql upon a submission of an input. We would send the input, and start polling the graphql until we have a response of output of that input.

**Comment by jplgarcia** [comment]
Makes sense, I can see advantages and disadvantages on my suggestion. Your idea is very good though!
