### ISSUE TITLE
Pre-deployed erc721 and 1155 tokens on localhost

### ISSUE THREAD

**Issue by jplgarcia** [sunodo/sunodo#420]
## 📚 Context

When developing a dApp that needs to interact with ERC721 and ERC1155 tokens the developers have to create a script to deploy those contracts whenever they are testing the application or rebuild it. It is a one time thing to get this setup, but it would expedite the process and in general improve quality of life for the developers if they had something already there to test.

## ✔️ Solution

Deploy ERC1155 and ERC721 smart contracts to the development environment on sunodo run (Sunodo Multi-Token and Sunodo NFT maybe?)

**Comment by tuler** [comment]
These contracts should be added to the `token` package, and integrated in the `devnet` package.
The solidity code can be generated by the OpenZeppeling wizard.
https://wizard.openzeppelin.com/#erc721
There are several options that can be selected there. That may impact the usability of the token by the developer. I'm not sure what is the ideal configuration.

**Comment by guidanoli** [comment]
Sunodo could deploy these contracts to devnet, with Alice (`0xf39Fd...92266`) being the owner.
It could also, optionally, mint 3-5 tokens already to cover the most basic use cases.

**Comment by tuler** [comment]
Is there a publicly available notorious NFT collection targeted for testing providing jsons following the [spec](https://eips.ethereum.org/EIPS/eip-721#specification)?

Or do we use a real one?

**Comment by guidanoli** [comment]
Maybe it would be nice to have Sunodo's own NFT collection, as a sort of easter egg, with images published to IPFS and all.

**Comment by tuler** [comment]
> Maybe it would be nice to have Sunodo's own NFT collection, as a sort of Easter egg, with images published to IPFS and all. Otherwise, there are plenty of repos with test data on GitHub, I believe. Just need to check their licenses.

We could pick a popular one, like Bored Apes, but I have no idea about licensing.
But I'm not sure if we need to pre-mint any tokens.

**Comment by guidanoli** [comment]
> > Maybe it would be nice to have Sunodo's own NFT collection, as a sort of Easter egg, with images published to IPFS and all. Otherwise, there are plenty of repos with test data on GitHub, I believe. Just need to check their licenses.
> 
> We could pick a popular one, like Bored Apes, but I have no idea about licensing. But I'm not sure if we need to pre-mint any tokens.

Yeah, maybe it would be even weird for your NFT store to start with some built-in tokens that have nothing to do with what you're doing? Like, if I'm doing NFTs of houses or party tickets, then an NFT of a Bored Ape would make no sense.
