### ISSUE TITLE
sunodo deploy should support AWS KMS

### ISSUE THREAD

**Issue by endersonmaia** [sunodo/sunodo#443]
## 📚 Context

After #383, it's possible to use sunodo to deploy your application to a public blockchain and self-host the validator.

In case it's needed to deploy to mainnet, the recommended way is to use a service like AWS KMS to hold the wallet.

## ✔️ Solution

`sunodo deploy` should be able to get the AWS credentials from the environment  + KSM Key ID  to make the deployment.

## 📈 Subtasks

-   [ ] add `--aws-kms-key-id` argument to `sunodo deploy` 

## 🎯 Definition of Done

-   [ ] sunodo user can deploy to mainnet/testnet using an AWS KMS key

**Comment by tuler** [comment]
Sunodo deploy is not actually running the node. The KMS params can still be specified when running the node.
What do you have in mind exactly? Improve the documentation, or actually change any code?

**Comment by endersonmaia** [comment]
I mean, today the user needs to pass a wallet via Metamask to deploy the contracts, I was thinking this could be done already using the KSM wallet.

I may be confusing the roles of application developer (deploy app contracts) vs validator (make claims (`Authority`))

**Comment by tuler** [comment]
> I may be confusing the roles of application developer (deploy app contracts) vs validator (make claims (`Authority`))

Exactly. The deployer can be any account.
The dapp owner is being set to the deployer, but can be transferred afterwards.
And the node wallet address is already manually entered in the deploy process. That has to be the KMS account address.
