### ISSUE TITLE
Mounts volume problem

### ISSUE THREAD

**Issue by omidasadpour** [sunodo/sunodo#444]
## 📚 Context

during the sunodo build, the process fails if the working directory was not in the `$HOME/*` directory, this is because of the docker desktop volumes permission. 

```
Error: Command failed with exit code 125: docker container run --detach --init --volume=./.sunodo/image.tar:/tmp/.sunodo/image.tar sunodo/sdk:0.3.0 sleep infinity
    docker: Error response from daemon: Mounts denied: 
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.    
```

## ✔️ Solution

We can have a document related to this problem and mention how to solve it in advanced, 
or, We can have a step during sunodo build process to check the working directory and maybe fix the problem by adding required permissions to the $PWD before running the container, 

## 🎯 Definition of Done

-   [ ] write a doc OR add an option on `build` sub command to add the required permissions

**Comment by endersonmaia** [comment]
This error will depends on where the `sunodo build` is executed. 

I don't know if we should mess with Docker Desktop configuration, since the message is already clear enough IMO.

Maybe we could have a special "Troubleshooting" section on our docs with cases like this.

**Comment by tuler** [comment]
I also think this should go to a "Troubleshooting" section of the documentation
