### ISSUE TITLE
Sunodo build fails with genext2fs locale error

### ISSUE THREAD

**Issue by tuler** [sunodo/sunodo#68]
## 🙂 Expected behavior

`sunodo build` to work with python template.

## 🫠 Actual behavior

```
 => => writing image sha256:e688f0854820172996808f31fb3048f0966ff1894f948fd5afd0e62236bce2a8                0.0s
genext2fs: archive_read_next_header(): Linkname can't be converted from UTF-8 to current locale.
    Error: Command failed with exit code 1: docker container run --rm --env USER=bart --env 
    GROUP=container-group-1000 --env UID=1000 --env GID=1000 --volume /tmp/dapp/.sunodo:/mnt sunodo/sdk:0.15.0 
    genext2fs --tarball /mnt/image.tar --block-size 4096 --faketime -r +2560 /mnt/image.ext2
```

## 🧪 Minimal test case

```
$ sunodo create dapp --template=python
$ cd dapp
$ sunodo build
```

## 🌎 Environment

> What is the environment that the bug happens?

## ✔️ Possible solutions

This is related to issue https://github.com/bestouff/genext2fs/pull/30
We can work around this by re-tarring the tar produced by `docker container export` with `gnu` format.
@mpolitzer used [bsdtar](https://github.com/cartesi/machine-emulator-tools/blob/f8df7d81f4d492f9ff8619444dfb95bc2267a8c8/example/build#L31) for that.
We don't have `bsdtar` in the `sunodo/sdk:0.15.0` image. Maybe it can work with `tar --format=gnu`, which we already have.

**Comment by tuler** [comment]
I tried to use `bsdtar` to re-tar it, and have the same error.

```
bsdtar -cf /mnt/image.gnutar --format=gnutar @/mnt/image.tar
bsdtar: Error reading archive /mnt/image.tar: Linkname can't be converted from UTF-8 to current locale.
bsdtar: Error exit delayed from previous errors.
```

the `/mnt/image.tar` file was produced by `docker export`.

**Comment by edubart** [comment]
This happened with me, my environment is ArchLinux, maybe relevant, my system locale is configured to `en_US.utf8`, that is:
```
$ locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```
