### ISSUE TITLE
Error Finishing Epoch

### ISSUE THREAD

**Issue by lynoferraz** [sunodo/sunodo#93]
## 🙂 Expected behavior

Finish epoch, make claims and generate proofs.

## 🫠 Actual behavior

Dispatcher error, machine loosing state and validator re sending inputs to the machine

## 🧪 Minimal test case

Create a voucher and increase time to claim epoch

## 🌎 Environment

Rollups version 0.9.0

[sunodo_epoch_error.txt](https://github.com/sunodo/sunodo/files/11677507/sunodo_epoch_error.txt)

**Comment by endersonmaia** [comment]
Sorry for the late reply.

First of all, which version of sunodo-cli did you use?

Please, test with https://github.com/sunodo/sunodo/releases/tag/%40sunodo%2Fcli%400.6.0 that uses the rollups-0.9.1

**Comment by endersonmaia** [comment]
> Is it a permission error?

The current cartesi node version needs to share this snapshots directory between server-manager and advance-runner, I'll investigate why this is happening.

**Comment by endersonmaia** [comment]
I'm assuming this only happens when running the docker engine on Linux. 

Using Docker Desktop for macOS|Linux|Windowshis should work fine since they use a VM and mount this via network somehow.
